#!/usr/bin/env bash
declare -r _ORIG_OPTIONS_=${-}
set -e
[[ -z "${1}" ]] && echo -e "Missing Parameter: PROJECT_DIR" >&2
set -u
declare -r _PROJECT_DIR_="${1}"
declare -r _PROJECT_FILE_='project.sh'
declare -r _PROJECT_CONFIGURATION_=${_PROJECT_DIR_}/${_PROJECT_FILE_}


if [[ -d ${_PROJECT_DIR_} ]]; then
    declare -r _IS_A_DIRECTORY_='21'
    echo "Is a directory: ${_IS_A_DIRECTORY_}:'${_PROJECT_DIR_}'" >&2
    exit ${_IS_A_DIRECTORY_}
else
    mkdir -p ${_PROJECT_DIR_}
fi

(
cat << PROJECT_CONFIGURATION 
#!/usr/bin/env bash
PROJECT_DIR="${_PROJECT_DIR_}"
PROJECT_FILE="${_PROJECT_FILE_}"

PROJECT_CONFIGURATION
) >  ${_PROJECT_CONFIGURATION_}


set ${_ORIG_OPTIONS_}
